config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }

  devise_scope :admin do
    get "dashboard", :to => "dashboard#index"
    get "dashboard/login", :to => "admins/sessions#new"
    post "dashboard/login", :to => "admins/sessions#create"
    get "dashboard/logout", :to => "admins/sessions#destroy"
  end

namespace :dashboard do
    resources :users, only: [:index, :destroy]
    resources :major_categories, except: [:new]
    resources :categories, except: [:new]
    resources :products, except: [:show]
    resources :orders, only: [:index]
end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "web#index"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  
  resource :users, only: [:edit, :update] do
   collection do
     get "cart", :to => "shopping_carts#index"
     post "cart/create", :to => "shopping_carts#create"
     delete "cart", :to => "shopping_carts#destroy"
     get "mypage", :to => "users#mypage"
     get "mypage/edit", :to => "users#edit"
     get "mypage/address/edit", :to => "users#edit_address"
     put "mypage", :to => "users#update"
     get "mypage/edit_password", :to =>"users#edit_password"
     put "mypage/password", :to => "users#update_password"
     get  "mypage/favorite", :to => "users#favorite"
     delete "mypage/delete", :to => "users#destroy"
     get    "mypage/cart_history",    :to => "users#cart_history_index", :as => "mypage_cart_histories"
     get    "mypage/cart_history/:num",    :to => "users#cart_history_show", :as => "mypage_cart_history"
     get    "mypage/register_card",     :to => "users#register_card"
     post   "mypage/token",             :to => "users#token"
     
   end
  end
  
  resources :products do
    member do
     get :favorite
    end
   resources :reviews, only: [:create]
 end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews
  acts_as_likeable
  has_one_attached :image

 extend DisplayList
 scope :on_category, -> (category) { where(category_id: category) }
 scope :sort_order, -> (order) { order(order) }

 scope :category_products, -> (category, page) { 
    on_category(category).
    display_list(page)
  }

 scope :sort_products, -> (sort_order, page) {
    on_category(sort_order[:sort_category]).
    sort_order(sort_order[:sort]).
    display_list(page)
  }
 
 scope :sort_list, -> { 
    {
      "並び替え" => "", 
      "価格の安い順" => "price asc",
      "価格の高い順" => "price desc", 
    }
  }
  
  scope :in_cart_product_names, -> (cart_item_ids) { where(id: cart_item_ids).pluck(:name).reverse }
  scope :recently_products, -> (number) { order(created_at: "desc").take(number) }
  scope :recommend_products, -> (number) { where(recommended_flag: true).take(number) }
  scope :check_products_carriage_list, -> (product_ids) { where(id: product_ids).pluck(:carriage_flag)}

  
  def reviews_new
    reviews.new
  end
  def reviews_with_id
    reviews.reviews_with_id
  end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: %w[show edit update destroy]
  layout "dashboard/dashboard"

  def index
    sort_query = []
    @sorted = ""

    if params[:sort].present?
      slices = split(' ', params[:sort])
      sort_query[slices[0]] = slices[1]
      @sorted = params[:sort]
    end

    if params[:keyword] != nil
      keyword = trim(params[:keyword])
      @total_count = Product.search_for_id_and_name(keyword).count
      @products = Product.search_for_id_and_name(keyword).sort_order(sort_query).display_list(params[:pages])
    else
      keyword = ""
      @total_count = Product.count
      @products = Product.display_list(params[:page])
    end

    @sort_list = Product.sort_list
    # redirect_to dashboard_products_path
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    product = Product.new(product_params)
    product.save
    redirect_to dashboard_products_path
  end

  def edit
    @categories = Category.all
  end

  def update
    @product.update(product_params)
    redirect_to dashboard_products_path
  end

  def destroy
    @product.destroy
    redirect_to dashboard_products_path
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :recommended_flag, :category_id, :shop_name, :carriage_flag, :image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :set_product, only: [:show, :create, :edit, :update, :destroy, :favorite]
  
  def index
    if sort_params.present?
     @category = Category.request_category(sort_params[:sort_category])
     @products = Product.sort_products(sort_params, params[:page])
    elsif params[:category].present?
     @category = Category.request_category(params[:category])
     @products = Product.category_products(@category, params[:page])
    else
     @products = Product.display_list(params[:page])
    end
     
     @major_category_names = Category.major_categories
     @categories = Category.all
     @sort_list = Product.sort_list
  end

  def show
    @reviews = @product.reviews_with_id
    @review = @reviews.new
    @star_repeat_select = Review.star_repeat_select
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end
  
  def favorite
   current_user.toggle_like!(@product)
   redirect_to product_url @product
  end
  
  private
  
   def set_product
      @product = Product.find(params[:id])
   end
   
   def product_params
      params.require(:product).permit(:name, :description, :price, :recommended_flag, :category_id)
   end

   def sort_params
     params.permit(:sort, :sort_category)
   end
   
end

app/helpers/dashboard/products_helper.rb
module Dashboard::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="row">
  <div class="col-2 sidebar-responsive-category">
      <div class="sidebar-pc"><%= render partial: "layouts/sidebar", locals: { categories: @categories, major_category_names: @major_category_names } %></div>
    </div>
  <div class="col-md-9 col-12">
    <div class="container">
     <% if @category.present? %>
       <%= link_to "トップ", "#", category: @major_category_name %> > <%= @category.name %>
       <h1><%= @category.name %>の商品一覧<%= @products.count %>件</h1>
       <%= form_with url: products_path, method: :get, local: true, class: "form-inline" do |f| %>
         <%= f.hidden_field :sort_category, value: @category.id %>
         並び替え
         <% if @sorted.present? %>
           <%= f.select :sort, @sort_list, selected: @sorted, onChange: "javascript: this.form.submit();", class: "form-inline ml-2" %>
         <% else %>
           <%= f.select :sort, @sort_list, {}, onChange: "javascript: this.form.submit();", class: "form-inline ml-2" %>
         <% end %>
       <% end %>
     <% end %>
   </div>
    <div class="container mt-4">
      <div class="row w-100">

        <% @products.each do |product|%>
        <div class="col-md-3 col-6">
          <%= link_to product_path(product) do %>
            <% if product.image.attached? %>
              <%= image_tag product.image, class: "img-thumbnail" %>
            <% else %>
              <%= image_tag "/images/dummy.png", class: "img-thumbnail" %>
            <% end %>
          <% end %>
          <div class="row">
            <div class="col-12">
              <p class="delimarche-product-label mt-2">
                <%= product.name %><br>
                <label>¥<%= product.price %></label>
              </p>
            </div>
          </div>
        </div>
        <% end %>

      </div>
    </div>
    <%= paginate @products %>
  </div>
</div>

app/views/products/show.html.erb
<div class="d-flex justify-content-center">
  <div class="row w-75">
    <div class="col-md-5 col-12">
      <% if @product.image.attached? %>
        <%= image_tag @product.image, class: "w-100 img-fuild" %>
      <% else %>
        <%= image_tag "/images/dummy.png", class: "w-100 img-fuild" %>
      <% end %>
    </div>

    <div class="col">
      <div class="d-flex flex-column">
        <p class="delimarche-product-shop-name">
          <%= image_tag "/images/map_icon.png", class:"icon-size" %>
          <%= @product.shop_name %>
          </p>
        <h1 class="">
          <%= @product.name %>
        </h1>
        <p class="">
          <%= @product.description %>
        </p>
        <hr>
        <p class="d-flex align-items-end">
          ￥<%= @product.price %>（税込）
        </p>
        <hr>
      </div>

      <% if user_signed_in? %>
        <%= form_with url: cart_create_users_path, local: true do |f| %>
         <%= f.hidden_field :product_id, value: @product.id %>
          <%= f.hidden_field :name, value: @product.name %>
          <%= f.hidden_field :price, value: @product.price %>
          <div class="form-group row">
            <%= f.label "数量", class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
              <%= f.number_field :quantity, min:1, value:1, class: "form-control w-25"%>
            </div>
          </div>
          <div class="row">
            <div class="col-md-7 col-6">
              <%= f.submit "カートに追加", class: "btn delimarche-submit-button w-100" do %>
                <i class="fas fa-shopping-cart"></i>
              <% end %>
            </div>
            <div class="col-md-5 col-5">
                 <%= link_to favorite_product_path, class: "btn delimarche-favorite-button text-favorite w-100" do %>
                <i class="fa fa-heart"></i><%= current_user.likes?(@product) ? "お気に入り解除" : "お気に入り" %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>

    <div class="offset-1 col-11">
      <hr class="w-100">
      <h3 class="float-left">カスタマーレビュー</h3>
    </div>

    <div class="offset-1 col-10">
      <div class="row">
       <% @reviews.each do |review| %>
       <div class="offset-md-5 col-md-5">
         <h3 class="review-score-color"><%= score_on_star(review.score) %></h3>
         <p class="h4"><%= review.content %></p>
          <h7><%= review.user.name %></h7>
          <h7><%= l review.created_at %></h7>
          <hr>
       </div>
       <% end %>
     </div>

     <% if user_signed_in? %>
       <div class="row">
          <div class="offset-md-5 col-md-5">
           <%= form_with model: @review, url: product_reviews_path(@product) do |f| %>
              <h5>評価</h5>
               <%= f.select :score, @star_repeat_select, {}, class: "form-control m-2 review-score-color" %>
              <h5>レビュー内容</h5>
             <%= f.text_area :content, class: "form-control m-2" %>
             <%= f.submit "レビューを追加" , class:"btn delimarche-submit-button ml-2"%>
           <% end %>
         </div>
       </div>
     <% end %>
    </div>
  </div>
</div>